### ISSUE TITLE
Página "não encontrada" ao clicar no logo pelo site

### ISSUE THREAD

**Issue by wricke** [ciawn/winners#101]
Entrei no site normalmente, e quando cliquei no logo da winners (canto superior esquerdo), caí numa página de erro...
Segue evidência:
![image](https://user-images.githubusercontent.com/39935313/115048433-f0b82f00-9eaf-11eb-98b4-bb49fb5e52b0.png)

**Comment by reginaldojunior** [comment]
Corrigido.
