### ISSUE TITLE
Integração com o Bling

### ISSUE THREAD

**Issue by reginaldojunior** [ciawn/winners#72]
Integrar vendas, produtos com o bling para poder emitir nota fiscal.

**Comment by thiagoalcav** [comment]
O Bling é um sistema de gestão praticamente concorrente do propósito do winners. Não acho que faz muito sentido criar uma integração com outro "erp" apenas para permitir emitir NF. Penso que seria mais interessante focar na integração com algum gateway de pagamento que ofereça o serviço de emissão de NF, como o Pagseguro ou o MercadoPago.

Acho inclusive a plataforma do MercadoPago mais interessante pensando em futuro, pois pode permitir certas integrações com o marketplace do MercadoLivre!

**Comment by reginaldojunior** [comment]
Opa @thiagoalcav realmente não faz sentindo integramos com a bling, quando pensei nisso a ideia seria mais em sentido da nota que já não é mais viável por ser um sistema concorrente e com outro objetivo deste e também que agora há outras altenativas como você mencionou. E acho que seria legal também, talvez criar um módulo próprio para isso no sistema aberto utilizando o nfephp ou outra biblioteca. 

Inclusive, vou fechar essa issue. Obrigado :smile:
